Fix typo. Split test of files presence to provide more specific error log.

diff --git a/installer/asbundle/scripts/as-unix-install.template b/installer/asbundle/scripts/as-unix-install.template
--- a/installer/asbundle/scripts/as-unix-install.template
+++ b/installer/asbundle/scripts/as-unix-install.template
@@ -14,16 +14,20 @@ export TMPDIR
 
 cd $INSTDIR
 echo "(`date`) Installing Appserver..." >> $LOGFILE
-if [ ! -f ./$EXECNAME -o ! -f $STATEFILE ] ; then
-	echo "ERROR: ./$ECEXNAME or $STATEFILE not found." >> $LOGFILE;
+if [ ! -f ./$EXECNAME ] ; then
+	echo "ERROR: ./$EXECNAME not found." >> $LOGFILE;
 	exit 2;
+fi
+if [ ! -f $STATEFILE ] ; then
+        echo "ERROR: $STATEFILE not found." >> $LOGFILE;
+        exit 3;
 fi
 
 if [ "$UNAME" = "Linux" -a ! -x "./$EXECNAME" ] ; then
 	/bin/chmod u+x ./$EXECNAME ./uninstall.sh;
 	if [ $? != 0 ] ; then
 		echo "ERROR: cannot add execute permissions to Appserver setup file." >> $LOGFILE;
-		exit 3;
+		exit 4;
 	fi
 fi
 
