Trying to switch to incremental build like trunk.

diff --git a/nbbuild/hudson/javadoc-nbms b/nbbuild/hudson/javadoc-nbms
--- a/nbbuild/hudson/javadoc-nbms
+++ b/nbbuild/hudson/javadoc-nbms
@@ -5,11 +5,15 @@ if [ `ant -f nbbuild/build.xml -Dmoduleconfig=daily-alpha-nbms print-cvs-modules
 then
     echo "Set of modules changed, getting fresh checkout..."
     rm -rf `ls | fgrep -v nbbuild`
-    ant -f nbbuild/build.xml -Dmoduleconfig=daily-alpha-nbms checkout || exit
+    ant -f nbbuild/build.xml -Dmoduleconfig=daily-alpha-nbms cvs-clean checkout || exit
+elif [ builds/`ls -1 ../builds | tail -2 | head -1` '!=' `readlink ../lastSuccessful` ]
+then
+    echo "Previous build failed, running clean build this time..."
+    ant -f nbbuild/build.xml cvs-clean || exit
 fi
 mydir=`cd $(dirname $0); pwd`
 keystore=$mydir/NBstore
 storepass=`cat $mydir/storepass`
-ant -emacs -Dbuildnum=$BUILD_TAG -Dmoduleconfig=daily-alpha-nbms -Dkeystore=$keystore -Dstorepass=$storepass -f nbbuild/build.xml cvs-clean merge build-nbms || exit
+ant -emacs -Dbuildnum=$BUILD_TAG -Dmoduleconfig=daily-alpha-nbms -Dkeystore=$keystore -Dstorepass=$storepass -f nbbuild/build.xml merge build-nbms || exit
 ant -f $mydir/build-update-descriptor.xml || exit
 ant -f nbbuild/build.xml -Djnlp.codebase=http://deadlock.netbeans.org/hudson/job/javadoc-nbms/lastSuccessfulBuild/artifact/nbbuild/build/jnlp/ -Djnlp.signjar.keystore=$keystore -Djnlp.signjar.alias=nb_ide -Djnlp.signjar.password=$storepass build-jnlp
