Jesse says it is better to use trap. Michal says it is better to use strip.

diff --git a/nbbuild/hudson/round-robin-push b/nbbuild/hudson/round-robin-push
--- a/nbbuild/hudson/round-robin-push
+++ b/nbbuild/hudson/round-robin-push
@@ -61,6 +61,18 @@ dobuild() {
     fi
 }
 
+rollback() {
+  EXIT="$?"
+  if [ -n "$BASETIP" ]; then
+    echo "Script failed with exitcode $EXIT rolling back to $BASETIP"
+    hg update -C
+    hg --config extensions.mq= strip -f -n "$BASETIP"
+    hg pull -r "$BASETIP"
+  else
+    echo "No rollback, exitcode $EXIT"
+  fi
+}
+
 if [ -z "$TMP" ]; then
   TMP="/tmp"
 fi
@@ -69,6 +81,9 @@ ANT_OPTS="-Xmx512m -XX:MaxPermSize=128m"
 export ANT_OPTS
 HGMERGE=merge
 export HGMERGE
+
+BASETIP=`hg id -i | tr -d "+"`
+trap rollback EXIT
 
 hg up -C tip
 hg --config extensions.purge= clean --all
@@ -88,7 +103,6 @@ else
     echo Build is not stable, exiting
     testresult "$TESTDIR" "check.build.stable" "`cat $STATUS`" "1"
     echo >"nbbuild/downstream-builder-not-stable-no-push.zip"
-    hg rollback
     exit 0
 fi
 
@@ -114,7 +128,6 @@ else
    else
      echo Merge failed.
      hg heads
-     hg rollback
      exit 7
    fi
    hg ci -u "$push_username"@netbeans.org -m 'Automated merge' || exit 8
@@ -128,16 +141,15 @@ if [ "$OUT_COUNT" -gt 0 ]; then
 else
     echo "No outgoing changes. No reason to do build."
     echo >"nbbuild/no-outgoing-changes-no-build.zip"
-    hg rollback
     exit 0
 fi
 
 
 if dobuild && hg push "$push_url"; then
     echo "Build and push successful"
+    unset BASETIP
     exit 0
 else
-    echo "Failure, rolling back own commits"
-    hg rollback
+    echo "Failure, rolling back own commits to $BASETIP"
     exit 1
 fi
