Reorganizing the code to fail the build when we cannot download previous test results

diff --git a/nbbuild/hudson/sigtests b/nbbuild/hudson/sigtests
--- a/nbbuild/hudson/sigtests
+++ b/nbbuild/hudson/sigtests
@@ -5,35 +5,39 @@ if [ -z "$JOB_URL" ]; then
 fi
 
 sigtest_prev=$WORKSPACE/nbbuild/build/prevsigtest/snapshot
-(
+if (
   mkdir -p $sigtest_prev && cd $sigtest_prev/.. && \
   wget "$JOB_URL""lastSuccessfulBuild/artifact/nbbuild/build/sigtest/snapshot/*zip*/snapshot.zip" &&
   unzip snapshot.zip
-) || exit 0
-echo SigTest: Previous Snapshots
-ls $sigtest_prev
-echo SigTest: Checking All Changes
-ANT_OPTS='-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/ant-check-sigtests.hprof' ant -Dsigtest.basedir=$sigtest_prev check-sigtests
-for report in `pwd`/nbbuild/build/sigtest/check-snapshot/*; do
-  if ! expr "$report" : ".*/TESTS-.*" && grep 'failures="1"' $report >/dev/null; then
-    sigtest_email=`cat $report | grep "^email:" | grep -v commit.mail | cut -c 8-`
-    if [ -z "$sigtest_email" ]; then
-      sigtest_email="api-changes@netbeans.org"
+) then
+    echo SigTest: Previous Snapshots
+    ls $sigtest_prev
+    echo SigTest: Checking All Changes
+    ANT_OPTS='-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/ant-check-sigtests.hprof' ant -Dsigtest.basedir=$sigtest_prev check-sigtests
+    for report in `pwd`/nbbuild/build/sigtest/check-snapshot/*; do
+    if ! expr "$report" : ".*/TESTS-.*" && grep 'failures="1"' $report >/dev/null; then
+        sigtest_email=`cat $report | grep "^email:" | grep -v commit.mail | cut -c 8-`
+        if [ -z "$sigtest_email" ]; then
+        sigtest_email="api-changes@netbeans.org"
+        fi
+        content=`cat $report`
+        (
+            echo "Code changes:";
+            echo "http://deadlock.netbeans.org/hudson/job/$JOB_NAME/$BUILD_NUMBER/changes"; 
+            echo "API changes:";
+            echo "http://deadlock.netbeans.org/hudson/job/$JOB_NAME/$BUILD_NUMBER/artifact/nbbuild/build/sigtest/check-snapshot/html/index.html"; 
+            echo "Failure output is available as StdErr output of sigtest test for appropriate module.";
+    #                echo "http://deadlock.netbeans.org/hudson/job/$JOB_NAME/$BUILD_NUMBER/artifact/$sigtest_out/`basename $report`"; 
+            echo; 
+            expr "$content" : ".*CDATA\[\(.*\)\]\].*"
+        ) | mail -s "`basename $report` - sigchanges in $JOB_NAME build #$BUILD_NUMBER" $sigtest_email
     fi
-    content=`cat $report`
-    (
-        echo "Code changes:";
-        echo "http://deadlock.netbeans.org/hudson/job/$JOB_NAME/$BUILD_NUMBER/changes"; 
-        echo "API changes:";
-        echo "http://deadlock.netbeans.org/hudson/job/$JOB_NAME/$BUILD_NUMBER/artifact/nbbuild/build/sigtest/check-snapshot/html/index.html"; 
-        echo "Failure output is available as StdErr output of sigtest test for appropriate module.";
-#                echo "http://deadlock.netbeans.org/hudson/job/$JOB_NAME/$BUILD_NUMBER/artifact/$sigtest_out/`basename $report`"; 
-        echo; 
-        expr "$content" : ".*CDATA\[\(.*\)\]\].*"
-    ) | mail -s "`basename $report` - sigchanges in $JOB_NAME build #$BUILD_NUMBER" $sigtest_email
-  fi
-done
-echo SigTest: Checking All Changes Done
+    done
+    echo SigTest: Checking All Changes Done
+else
+    echo SigTest: Cannot download previous Snapshot
+    exit 2
+fi
 
 echo SigTest: Generating Golden Files
 ant gen-sigtests || exit 1
