If an incremental build fails, don't restart it; just do a clean build next time.

diff --git a/nbbuild/hudson/trunk b/nbbuild/hudson/trunk
--- a/nbbuild/hudson/trunk
+++ b/nbbuild/hudson/trunk
@@ -5,6 +5,10 @@ then
     echo "Set of modules changed, getting fresh checkout..."
     rm -rf `ls | fgrep -v nbbuild`
     ant -f nbbuild/build.xml checkout cvs-clean || exit
+elif [ builds/`ls -1 ../builds | tail -2 | head -1` '!=' `readlink ../lastSuccessful` ]
+then
+    echo "Previous build failed, running clean build this time..."
+    ant -f nbbuild/build.xml cvs-clean || exit
 fi
 for www in */www
 do
@@ -14,4 +18,4 @@ do
         cp -r nbbuild/dummy $www
     fi
 done
-ant -emacs -Dbuildnum=$BUILD_TAG -f nbbuild/build.xml all || ant -emacs -Dbuildnum=$BUILD_TAG -f nbbuild/build.xml cvs-clean all
+ant -emacs -Dbuildnum=$BUILD_TAG -f nbbuild/build.xml all
