#123673: NetBeans does not start and does not explain why (added check for DISPLAY variable)

diff --git a/o.n.bootstrap/launcher/unix/nbexec b/o.n.bootstrap/launcher/unix/nbexec
--- a/o.n.bootstrap/launcher/unix/nbexec
+++ b/o.n.bootstrap/launcher/unix/nbexec
@@ -41,6 +41,12 @@
 
 PRG=$0
 
+# Check DISPLAY variable
+if [ "no$DISPLAY" = "no" ]; then
+    echo "$0: ERROR: environment variable DISPLAY is not set"
+    exit 2
+fi
+
 resolve_symlink () {
     file="$1"
     while [ -h "$file" ]; do
